import type { Project } from "./types";

/**
 * Source: Master Source of Truth §9 (Initial project database) for the five
 * projects with fuller scope descriptions, and the brochure's "Our Landmark
 * Projects" photo captions (pp. 39–43) for the lighter portfolio entries —
 * name, client and location only, since the brochure gives no further scope
 * detail for those. No challenge/engineering-approach/outcome narrative is
 * invented anywhere below; fields with no supplied source content are left
 * undefined so the case-study template renders an honest empty state rather
 * than fabricated prose. Huawei Technologies Nepal is deliberately excluded
 * despite appearing in the brochure photo grid — the client questionnaire
 * (the higher-authority, more recent source) states Huawei should not be
 * photographed/publicised. See docs/OPEN_DECISIONS.md #4–#5. (2026-10-01:
 * the client's own changelist now names Huawei — in the client register,
 * src/content/clients.ts, and the Electrical "Huawei NT data centre" line —
 * so it is named, but still not photographed or written up as a case study.)
 */
export const projects: Project[] = [
  // 2026-10-05 client: Yak & Yeti leads the portfolio ("can be the first
  // photo"); its new heritage-wing photo (Drive, 2026-09-30) is the hero.
  {
    slug: "hotel-yak-and-yeti",
    name: "Hotel Yak & Yeti",
    client: "Hotel Yak & Yeti",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/hotel-yak-and-yeti-heritage.jpg", alt: "Hotel Yak & Yeti, Kathmandu: the heritage palace wing", width: 678, height: 452 },
    gallery: [
      { src: "/images/projects/hotel-yak-and-yeti.jpg", alt: "Hotel Yak & Yeti, Kathmandu: the hotel wing and garden", width: 1024, height: 575 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Hotel Yak & Yeti, Kathmandu",
      description: "Hotel Yak & Yeti, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hotel-barahi-kathmandu",
    name: "Hotel Barahi Kathmandu",
    client: "Hotel Barahi Kathmandu",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/landmarks/hotel-barahi-kathmandu.jpg",
      alt: "Hotel Barahi Kathmandu — rooftop pool and terrace at night", width: 1024, height: 576 },
    gallery: [
      { src: "/images/landmarks/hotel-barahi-kathmandu-facade.jpg", alt: "Hotel Barahi Kathmandu, street facade", width: 863, height: 575 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["hyatt-place-kathmandu", "radisson-hotel-kathmandu"],
    featured: true,
    seo: {
      title: "Hotel Barahi Kathmandu",
      description: "Hotel Barahi Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // Corrected 2026-09-24 — this entry's own heroImage photo has "HYATT
    // PLACE" clearly signed on the building itself, not "Hyatt Centric";
    // these are different Hyatt sub-brands (Place = select-service,
    // Centric = boutique lifestyle), so this was a naming/labeling error,
    // not a duplicate to merge. Renamed to match the actual photographed
    // building rather than continuing to publish a mismatched name. See
    // "hyatt-regency-kathmandu" below for the separate, genuinely different
    // Hyatt property newly photographed.
    slug: "hyatt-place-kathmandu",
    name: "Hyatt Place",
    client: "Hyatt Place",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/hyatt-place-kathmandu.jpg", alt: "Hyatt Place, Kathmandu", width: 700, height: 467 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["dusit-princess", "tiger-palace-resort", "hotel-barahi-kathmandu", "hyatt-regency-kathmandu"],
    featured: true,
    seo: {
      title: "Hyatt Place, Kathmandu",
      description: "Hyatt Place, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hyatt-regency-kathmandu",
    name: "Hyatt Regency Kathmandu",
    client: "Hyatt Regency Kathmandu",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/landmarks/hyatt-regency-kathmandu.jpg",
      alt: "Hyatt Regency Kathmandu, at dusk",
      width: 2000,
      height: 1125,
    },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["hyatt-place-kathmandu", "dusit-princess"],
    featured: true,
    seo: {
      title: "Hyatt Regency Kathmandu",
      description: "Hyatt Regency Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "aloft-kathmandu-thamel",
    name: "Aloft Kathmandu Thamel",
    client: "Aloft Kathmandu Thamel",
    clientDisplayApproved: true,
    location: "Thamel, Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/landmarks/aloft-kathmandu-thamel.jpg",
      alt: "Aloft Kathmandu Thamel",
      width: 2400,
      height: 1600,
    },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["hotel-barahi-kathmandu", "holiday-inn-express"],
    featured: true,
    seo: {
      title: "Aloft Kathmandu Thamel",
      description: "Aloft Kathmandu Thamel. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // "Shinta Mani" branded properties are Bill Bensley's boutique lodge
    // collection; Shinta Mani Mustang (Upper Mustang) is the one Nepal
    // property, and matches this photo's stone-and-timber, Tibetan-
    // influenced architecture (endless-knot carved doors) — not a generic
    // international hotel aesthetic. Named on that visual match; flag for
    // direct confirmation if a different Shinta Mani property is meant.
    slug: "shinta-mani-mustang",
    name: "Shinta Mani Mustang",
    client: "Shinta Mani Mustang",
    clientDisplayApproved: true,
    location: "Mustang, Nepal",
    industrySlug: "hospitality",
    projectType: "Resort",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/landmarks/shinta-mani-mustang.jpg",
      alt: "Shinta Mani Mustang",
      width: 1920,
      height: 1080,
    },
    gallery: [
      { src: "/images/projects/shinta-mani-mustang-2.jpg", alt: "Shinta Mani Mustang, stone guest wings", width: 1536, height: 865 },
      { src: "/images/projects/shinta-mani-mustang-3.jpg", alt: "Shinta Mani Mustang against the Himalaya", width: 1366, height: 768 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["tiger-palace-resort", "the-terrace-resort-lalitpur"],
    featured: false,
    seo: {
      title: "Shinta Mani Mustang",
      description: "Shinta Mani Mustang. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "radisson-hotel-kathmandu",
    name: "Radisson Hotel Kathmandu",
    client: "Hotel Radisson",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/radisson-hotel-kathmandu.jpg", alt: "Radisson Hotel Kathmandu, Lazimpat", width: 2400, height: 1176, credit: "Photo: Sgroey / CC BY-SA 4.0, via Wikimedia Commons" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["the-soaltee"],
    featured: true,
    seo: {
      title: "Radisson Hotel Kathmandu",
      description: "Radisson Hotel, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "holiday-inn-express",
    name: "Holiday Inn Express",
    client: "Holiday Inn Express",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/holiday-inn-express.jpg", alt: "Holiday Inn Express, Kathmandu", width: 960, height: 560 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Holiday Inn Express, Kathmandu",
      description: "Holiday Inn Express, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // Merged 2026-09-28 with a duplicate "The Terraces Resort & Spa" entry:
    // the client's own photo is filed as "The Terraces Resort & Spa,
    // Lalitpur", confirming one property. Old slug redirects here.
    slug: "the-terrace-resort-lalitpur",
    name: "The Terraces Resort & Spa",
    client: "The Terraces Resort & Spa",
    clientDisplayApproved: true,
    location: "Lalitpur",
    industrySlug: "hospitality",
    projectType: "Resort & spa",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/the-terraces-resort-spa.jpg", alt: "The Terraces Resort & Spa, Lalitpur", width: 1360, height: 1020 },
    gallery: [
      { src: "/images/landmarks/the-terrace-resort-lalitpur.jpg", alt: "The Terraces Resort & Spa, pool terrace", width: 1024, height: 768 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["tiger-palace-resort", "chandragiri-hills-resort"],
    featured: true,
    seo: {
      title: "The Terraces Resort & Spa, Lalitpur",
      description: "The Terraces Resort & Spa, Lalitpur. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  // Extended landmark list — AIPL PROFILE - 2026.pptx slides 8–11, "Our Landmark
  // Projects" (name + location only, no scope given in the source). Same
  // minimal, non-fabricated pattern as the entries above. See
  // docs/AIRTECH_CONTENT_AUDIT.md §2d.
  {
    slug: "tiger-palace-resort",
    name: "Tiger Palace Resort",
    client: "Tiger Palace Resort & Casino",
    clientDisplayApproved: true,
    location: "Bhairahawa, Nepal",
    industrySlug: "hospitality",
    projectType: "Resort & casino",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/tiger-palace-resort.jpg", alt: "Tiger Palace Resort, Bhairahawa", width: 1024, height: 576 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["dusit-princess", "hyatt-place-kathmandu"],
    featured: true,
    seo: {
      title: "Tiger Palace Resort",
      description: "Tiger Palace Resort, Bhairahawa. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "chandragiri-hills-resort",
    name: "Chandragiri Hills Resort",
    client: "Chandragiri Hills Resort",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Resort",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/chandragiri-hills-resort.jpg", alt: "Chandragiri Hills Resort, Kathmandu", width: 2400, height: 1347 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["tiger-palace-resort"],
    featured: true,
    seo: {
      title: "Chandragiri Hills Resort",
      description: "Chandragiri Hills Resort, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "dusit-princess",
    name: "Dusit Princess",
    client: "Dusit Princess",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/dusit-princess.jpg", alt: "Dusit Princess, Kathmandu", width: 2400, height: 1088 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["tiger-palace-resort", "hyatt-place-kathmandu"],
    featured: true,
    seo: {
      title: "Dusit Princess, Kathmandu",
      description: "Dusit Princess, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "fairfield-by-marriott-thamel",
    name: "Fairfield by Marriott, Thamel",
    client: "Nepal Hospitality & Hotel (P) Ltd.",
    clientDisplayApproved: true,
    location: "Thamel, Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "completed",
    airtechRole: "Full MEP works.",
    servicesDelivered: ["MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    heroImage: {
      src: "/images/projects/fairfield-by-marriott-thamel.jpg",
      alt: "Fairfield by Marriott, Thamel, Kathmandu",
      width: 377,
      height: 671,
    },
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["tiger-palace-resort"],
    featured: false,
    seo: {
      title: "Fairfield by Marriott, Thamel: Full MEP",
      description: "Full MEP works delivered at Fairfield by Marriott, Thamel, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "the-soaltee",
    name: "The Soaltee",
    client: "Soaltee",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/the-soaltee.jpg", alt: "The Soaltee, Kathmandu", width: 1080, height: 607 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["radisson-hotel-kathmandu"],
    featured: false,
    seo: {
      title: "The Soaltee, Kathmandu",
      description: "The Soaltee, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hotel-hilton-naxal",
    name: "Hotel Hilton",
    client: "Hotel Hilton",
    clientDisplayApproved: true,
    location: "Naxal, Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Hotel Hilton, Naxal",
      description: "Hotel Hilton, Naxal, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "nepali-ghar-hotel",
    name: "Nepali Ghar Hotel",
    client: "Nepali Ghar Hotel",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/nepali-ghar-hotel.jpg", alt: "Nepali Ghar Hotel, Thamel, Kathmandu", width: 1042, height: 1020 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Nepali Ghar Hotel, Kathmandu",
      description: "Nepali Ghar Hotel, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // Added 2026-10-05 from the client's Drive photo "Met Life in the
    // Plaza". The client asked that it be named exactly this way: MetLife's
    // space in The Plaza building, not The Plaza as a whole. Scope beyond
    // the name is not supplied.
    slug: "metlife-the-plaza",
    name: "MetLife in The Plaza",
    client: "MetLife",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "MetLife's offices in The Plaza building. Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/metlife-the-plaza.jpg", alt: "The Plaza, Kathmandu, home of MetLife's offices", width: 900, height: 669 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["ncell-corporate-office"],
    featured: true,
    seo: {
      title: "MetLife in The Plaza, Kathmandu",
      description: "MetLife's offices in The Plaza, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "ncell-corporate-office",
    name: "Ncell Corporate Office",
    client: "Ncell",
    clientDisplayApproved: true,
    location: "Lainchaur, Kathmandu",
    industrySlug: "telecom-data-centres",
    projectType: "Corporate office",
    projectStatus: "completed",
    airtechRole: "HVAC and MEP works for the new corporate office.",
    servicesDelivered: ["HVAC", "MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health"],
    // Reconciled with "Ncell Iconic Building, Kathmandu" (AIPL PROFILE - 2026.pptx, slide 8)
    // per docs/AIRTECH_CONTENT_AUDIT.md §2d — same client, treated as the same entry.
    heroImage: { src: "/images/projects/ncell-corporate-office.jpg", alt: "Ncell Iconic Building, Kathmandu", width: 1600, height: 1066 },
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health"],
    relatedProjectSlugs: ["sipradi-trading"],
    featured: true,
    seo: {
      title: "Ncell Corporate Office: HVAC & MEP",
      description: "HVAC and MEP works delivered for the Ncell corporate office in Lainchaur, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "sipradi-trading",
    name: "Sipradi Trading Corporate Office",
    client: "Sipradi Trading Pvt. Ltd.",
    clientDisplayApproved: true,
    location: "Gairidhara, Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "completed",
    airtechRole: "Complete MEP and HVAC works for the new office building.",
    servicesDelivered: ["Complete MEP", "HVAC"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    heroImage: { src: "/images/projects/sipradi-trading.jpg", alt: "Sipradi showroom and office building, Gairidhara, Kathmandu", width: 800, height: 1067 },
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["ncell-corporate-office"],
    featured: true,
    seo: {
      title: "Sipradi Trading Corporate Office: Complete MEP",
      description: "Complete MEP and HVAC works delivered for the Sipradi Trading office building in Gairidhara, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "new-airport-commercial-office-parking",
    name: "New Airport Commercial Office & Parking Lot",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Infrastructure / commercial",
    projectStatus: "provisional",
    airtechRole: "MEP works for the commercial office and parking facility.",
    servicesDelivered: ["MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health"],
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "New Airport Commercial Office & Parking: MEP",
      description: "MEP works for the new airport commercial office and parking lot facility in Kathmandu.",
    },
    status: "needs_verification",
  },
  {
    slug: "nobel-college-health-education",
    name: "Nobel College of Health and Education Foundation",
    client: "Nobel College of Health and Education Foundation",
    clientDisplayApproved: true,
    location: "Baneshwor, Kathmandu",
    industrySlug: "education-institutional",
    projectType: "Healthcare / education",
    projectStatus: "completed",
    airtechRole: "MEP works including supply, delivery, installation, testing and commissioning.",
    servicesDelivered: ["MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["nepal-mediciti"],
    featured: true,
    seo: {
      title: "Nobel College of Health and Education Foundation: MEP",
      description: "MEP works including supply, delivery, installation, testing and commissioning at Nobel College, Baneshwor, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "nepal-mediciti",
    name: "Nepal Mediciti / Ashwin's Medical College & Hospital",
    client: "Nepal Mediciti / Ashwin's Medical College & Hospital",
    clientDisplayApproved: true,
    location: "Lalitpur, Nepal",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "completed",
    airtechRole: "HVAC/MEP engineering and execution.",
    servicesDelivered: ["HVAC", "MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    heroImage: { src: "/images/projects/nepal-mediciti.jpg", alt: "Nepal Mediciti hospital, Lalitpur", width: 1776, height: 1080 },
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["nobel-college-health-education"],
    featured: true,
    seo: {
      title: "Nepal Mediciti Hospital: HVAC & MEP",
      description: "HVAC/MEP engineering and execution at Nepal Mediciti / Ashwin's Medical College & Hospital.",
    },
    status: "needs_verification",
  },
  // Lighter portfolio entries — brochure "Our Landmark Projects" photo captions only.
  // No scope narrative supplied, so challenge/approach/outcome fields are omitted.
  {
    slug: "norvic-international-hospital",
    name: "Norvic International Hospital",
    client: "Norvic International Hospital",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/norvic-international-hospital.jpg", alt: "Norvic International Hospital, Kathmandu", width: 1024, height: 706 },
    gallery: [
      { src: "/images/projects/norvic-international-hospital-2.jpg", alt: "Norvic International Hospital main entrance at night", width: 2400, height: 1350, credit: "Photo: सरोज_कुमार_ढकाल / CC BY-SA 3.0, via Wikimedia Commons" },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Norvic International Hospital",
      description: "Norvic International Hospital, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "grande-international-hospital",
    name: "Grande International Hospital",
    client: "Grande International Hospital",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/projects/grande-international-hospital.jpg",
      alt: "Grande International Hospital, Kathmandu",
      width: 2000,
      height: 1333,
    },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["frontline-hospital"],
    featured: false,
    seo: {
      title: "Grande International Hospital",
      description: "Grande International Hospital, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "frontline-hospital",
    name: "Frontline Hospital",
    client: "Frontline Hospital",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/projects/frontline-hospital.jpg",
      alt: "Frontline Hospital, Kathmandu",
      width: 2400,
      height: 1597,
    },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["grande-international-hospital"],
    featured: false,
    seo: {
      title: "Frontline Hospital",
      description: "Frontline Hospital, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "universal-college-medical-sciences",
    name: "Universal College of Medical Sciences",
    client: "Universal College of Medical Sciences",
    clientDisplayApproved: true,
    location: "Bhairahawa",
    industrySlug: "education-institutional",
    projectType: "Educational / medical college",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/projects/universal-college-medical-sciences.jpg",
      alt: "Universal College of Medical Sciences, Bhairahawa", width: 1200, height: 436 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["chitwan-medical-college"],
    featured: true,
    seo: {
      title: "Universal College of Medical Sciences",
      description: "Universal College of Medical Sciences, Bhairahawa. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "chitwan-medical-college",
    name: "Chitwan Medical College",
    client: "Chitwan Medical College Teaching Hospital",
    clientDisplayApproved: true,
    location: "Bharatpur, Chitwan",
    industrySlug: "education-institutional",
    projectType: "Educational / medical college & teaching hospital",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/chitwan-medical-college.jpg", alt: "Chitwan Medical College Teaching Hospital, Bharatpur", width: 2400, height: 1391 },
    gallery: [
      { src: "/images/projects/chitwan-medical-college-2.jpg", alt: "Chitwan Medical College campus and teaching hospital", width: 768, height: 512 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["universal-college-medical-sciences", "global-college"],
    featured: false,
    seo: {
      title: "Chitwan Medical College",
      description: "Chitwan Medical College Teaching Hospital, Bharatpur. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "global-college",
    name: "Global College International",
    client: "Global College International",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "education-institutional",
    projectType: "Educational institution",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/projects/global-college.jpg",
      alt: "Global College International, Kathmandu",
      width: 2400,
      height: 1597,
    },
    gallery: [
      { src: "/images/projects/global-college-2.jpg", alt: "Global College International, front entrance", width: 1600, height: 2405 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["chitwan-medical-college", "universal-college-medical-sciences"],
    featured: false,
    seo: {
      title: "Global College International",
      description: "Global College International, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // Filename supplied as "Marwadi Parishad" — the building's own visible
    // signage (Dibyaratna Consultant, an HBL bank branch, a gallery) belongs
    // to current tenants, which doesn't contradict that name (a community
    // association/trust building often carries tenant signage rather than
    // its own on the facade). Treated as the client name per the supplied
    // filename, per this site's standing rule for user-supplied project
    // photography; flag for correction if that's not the intended building.
    slug: "marwadi-parishad",
    name: "Marwadi Parishad",
    client: "Marwadi Parishad",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Institutional / mixed-use building",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/projects/marwadi-parishad.jpg",
      alt: "Marwadi Parishad, Kathmandu",
      width: 1597,
      height: 2400,
    },
    gallery: [
      { src: "/images/projects/marwadi-parishad-2.jpg", alt: "Marwadi Parishad from the street corner", width: 2400, height: 3607 },
      { src: "/images/projects/marwadi-parishad-3.jpg", alt: "Rooftop air-conditioning outdoor unit at Marwadi Parishad", width: 2400, height: 1597 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["shanker-group-corporate-office"],
    featured: false,
    seo: {
      title: "Marwadi Parishad",
      description: "Marwadi Parishad, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "shanker-group-corporate-office",
    name: "Shanker Group Corporate Office",
    client: "Shanker Group",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: {
      src: "/images/landmarks/shanker-group-corporate-office.jpg",
      alt: "Shanker Group Corporate Office (Jagdamba Building), Tangal, Kathmandu",
      width: 2000,
      height: 1335,
    },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Shanker Group Corporate Office",
      description: "Shanker Group Corporate Office, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "caan-civil-aviation-authority",
    name: "CAAN Office Building",
    client: "Civil Aviation Authority of Nepal",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Infrastructure / institutional",
    projectStatus: "completed",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    // AIPL PROFILE - 2026.pptx, slide 8 — "CAAN Office Building, Kathmandu".
    heroImage: { src: "/images/projects/caan-office-building.jpg", alt: "CAAN Office Building, Kathmandu", width: 872, height: 654 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["new-airport-commercial-office-parking"],
    featured: true,
    seo: {
      title: "Civil Aviation Authority of Nepal (CAAN)",
      description: "Civil Aviation Authority of Nepal (CAAN), Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "laxmi-motor-corporation",
    name: "Laxmi Motors KD Plant",
    client: "Laxmi Motor Corporation",
    clientDisplayApproved: true,
    location: "Parasi, Nepal",
    industrySlug: "industrial",
    projectType: "Industrial facility",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    // AIPL PROFILE - 2026.pptx, slide 8 — "Laxmi Motors KD Plant, Parasi"; reconciled with the
    // existing "Laxmi Motor Corporation" client record per docs/AIRTECH_CONTENT_AUDIT.md §2d.
    heroImage: { src: "/images/projects/laxmi-motors-kd-plant.jpg", alt: "Laxmi Motors KD Plant, Parasi", width: 1200, height: 686 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Laxmi Motor Corporation",
      description: "Laxmi Motor Corporation, Parasi. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "skyline-mall-birgunj",
    name: "Skyline Mall",
    client: "Skyline Mall",
    clientDisplayApproved: true,
    location: "Birgunj, Nepal",
    industrySlug: "corporate-commercial",
    projectType: "Retail / commercial",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    // heroImage removed 2026-09-14 — the only sourced file is a pre-
    // construction 3D render (not a photo of the actual building) at
    // 523x238, whose wide/short aspect crops badly into the site's 4:3
    // card treatment. Per "all images used should be high quality," this
    // now renders as the honest no-photo list row, same as every other
    // project with no sourced photograph, rather than a soft, misleading
    // render passed off as project photography.
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Skyline Mall, Birgunj",
      description: "Skyline Mall, Birgunj. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hgi-corporate-office",
    name: "HGI Corporate Office",
    client: "HGI",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "HGI Corporate Office, Kathmandu",
      description: "HGI Corporate Office, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // Explicitly marked "(Ongoing)" in the source — never present as a
    // completed case study. See docs/AIRTECH_CONTENT_AUDIT.md §2d.
    slug: "parliament-building",
    name: "Parliament Building",
    clientDisplayApproved: false,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Government / institutional building",
    projectStatus: "ongoing",
    airtechRole: "Ongoing project featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/parliament-building.jpg", alt: "Federal Parliament building (International Convention Centre), New Baneshwor, Kathmandu", width: 2400, height: 1349, credit: "Photo: Bijay Chaurasia / CC BY-SA 4.0, via Wikimedia Commons" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Parliament Building, Kathmandu (Ongoing)",
      description: "Parliament Building, Kathmandu: an ongoing project in Airtech's portfolio.",
    },
    status: "source_only",
  },
  // Named directly in AIPL PROFILE - 2026.pptx's appreciation-certificate
  // scans (slides 19–21) — real, signed client reference letters. Exact
  // contract values and capacities from those letters are deliberately not
  // reproduced here (see docs/AIRTECH_CONTENT_AUDIT.md §2b) — only name,
  // location and the general scope character, same minimal treatment as the
  // other portfolio-only entries above.
  {
    slug: "nepal-cancer-hospital",
    name: "Nepal Cancer Hospital & Research Center",
    client: "Nepal Cancer Hospital & Research Center",
    clientDisplayApproved: true,
    location: "Harisiddhi, Lalitpur",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "completed",
    airtechRole: "Full MEP: supply, delivery, installation, testing and commissioning.",
    servicesDelivered: ["MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["grande-international-hospital"],
    featured: false,
    seo: {
      title: "Nepal Cancer Hospital & Research Center: Full MEP",
      description: "Full MEP: supply, delivery, installation, testing and commissioning at Nepal Cancer Hospital & Research Center, Lalitpur.",
    },
    status: "source_only",
  },
  {
    slug: "jica-nepal-office",
    name: "JICA Nepal Office",
    client: "JICA Nepal Office",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "embassies-ingos",
    projectType: "INGO office",
    projectStatus: "completed",
    airtechRole: "HVAC: supply, installation, testing and commissioning.",
    servicesDelivered: ["HVAC"],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["british-embassy-kathmandu"],
    featured: false,
    seo: {
      title: "JICA Nepal Office: HVAC",
      description: "HVAC supply, installation, testing and commissioning at the JICA Nepal Office, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "british-embassy-kathmandu",
    name: "British Embassy Kathmandu: Visa Consular Building",
    client: "British Embassy Kathmandu",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "embassies-ingos",
    projectType: "Embassy",
    projectStatus: "completed",
    airtechRole: "HVAC: design, supply, installation, testing and commissioning for the new Visa Consular Building.",
    servicesDelivered: ["HVAC"],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/recognition/british-embassy-kathmandu.jpg", alt: "British Embassy, Kathmandu", width: 401, height: 632 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["jica-nepal-office"],
    featured: false,
    seo: {
      title: "British Embassy Kathmandu: HVAC",
      description: "HVAC design, supply, installation, testing and commissioning for the British Embassy Kathmandu's Visa Consular Building.",
    },
    status: "source_only",
  },

  // Added 2026-09-29 from the client's per-project photo folders
  // (ASSETS/MIT college, Golyan Towers, Jai Nepal, NOVA) and
  // ASSETS/images/Kavya Resort.jpg. Jai Nepal Cinema–QFX is named in the
  // AIPL PROFILE deck's clients slide; the others are identified by the
  // client's own folder/file names. Same minimal, non-fabricated pattern:
  // no scope, year or capacity invented; locations only where known.
  {
    slug: "mit-college",
    name: "MIT College",
    client: "MIT College",
    clientDisplayApproved: true,
    industrySlug: "education-institutional",
    projectType: "College",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/mit-college.jpg", alt: "MIT College building", width: 2400, height: 3608 },
    gallery: [
      { src: "/images/projects/mit-college-2.jpg", alt: "Rooftop air-conditioning outdoor units at MIT College", width: 2400, height: 1597 },
      { src: "/images/projects/mit-college-3.jpg", alt: "Classroom with ceiling cassette units and exposed ducting", width: 2400, height: 1597 },
      { src: "/images/projects/mit-college-4.jpg", alt: "Ceiling cassette and refrigerant piping detail", width: 2400, height: 1597 },
      { src: "/images/projects/mit-college-5.jpg", alt: "Office floor with ducted air distribution", width: 2400, height: 1597 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "MIT College",
      description: "MIT College. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "golyan-tower",
    name: "Golyan Tower",
    client: "Golyan Tower",
    clientDisplayApproved: true,
    industrySlug: "corporate-commercial",
    projectType: "Commercial tower",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/golyan-tower.jpg", alt: "Golyan Tower", width: 1597, height: 2400 },
    gallery: [
      { src: "/images/projects/golyan-tower-2.jpg", alt: "Golyan Tower reception with ceiling cassette units", width: 2400, height: 1597 },
      { src: "/images/projects/golyan-tower-3.jpg", alt: "Golyan Tower multipurpose hall", width: 2400, height: 1597 },
      { src: "/images/projects/golyan-tower-4.jpg", alt: "Golyan Tower lounge and corridor", width: 2400, height: 1597 },
      { src: "/images/projects/golyan-tower-5.jpg", alt: "Rooftop air-conditioning plant at Golyan Tower", width: 2400, height: 1597 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Golyan Tower",
      description: "Golyan Tower. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "jai-nepal-cinema",
    name: "Jai Nepal Cinema (QFX)",
    client: "Jai Nepal Cinema (QFX)",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "auditoriums-studios",
    projectType: "Cinema",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/jai-nepal-cinema.jpg", alt: "Jai Nepal Cinema (QFX), Kathmandu", width: 2400, height: 1597 },
    gallery: [
      { src: "/images/projects/jai-nepal-cinema-2.jpg", alt: "Jai Nepal Cinema lobby", width: 2400, height: 1597 },
      { src: "/images/projects/jai-nepal-cinema-3.jpg", alt: "Platinum screen foyer with cassette units", width: 2400, height: 1597 },
      { src: "/images/projects/jai-nepal-cinema-4.jpg", alt: "Concessions area", width: 2400, height: 1597 },
      { src: "/images/projects/jai-nepal-cinema-5.jpg", alt: "Air-conditioning outdoor units in the plant area", width: 1597, height: 2400 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Jai Nepal Cinema (QFX), Kathmandu",
      description: "Jai Nepal Cinema (QFX). Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "club-nova",
    name: "Club NOVA",
    client: "Club NOVA",
    clientDisplayApproved: true,
    industrySlug: "corporate-commercial",
    projectType: "Entertainment venue",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/club-nova.jpg", alt: "Club NOVA exterior", width: 2400, height: 1597 },
    gallery: [
      { src: "/images/projects/club-nova-2.jpg", alt: "Club NOVA main floor and stage", width: 2400, height: 1597 },
      { src: "/images/projects/club-nova-3.jpg", alt: "Club NOVA bar", width: 2400, height: 1597 },
      { src: "/images/projects/club-nova-4.jpg", alt: "Supply-air diffusers on the Club NOVA ceiling", width: 2400, height: 1597 },
      { src: "/images/projects/club-nova-5.jpg", alt: "Indoor unit and ductwork above the ceiling", width: 2400, height: 1597 },
    ],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Club NOVA",
      description: "Club NOVA. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "kavya-resort",
    name: "Kavya Resort",
    client: "Kavya Resort",
    clientDisplayApproved: true,
    industrySlug: "hospitality",
    projectType: "Resort",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/projects/kavya-resort.jpg", alt: "Kavya Resort", width: 500, height: 500 },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Kavya Resort",
      description: "Kavya Resort. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
];

export function getProjects() {
  return projects;
}

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}

export function getFeaturedProjects() {
  return projects.filter((p) => p.featured);
}

export function getProjectsByIndustry(industrySlug: string) {
  return projects.filter((p) => p.industrySlug === industrySlug);
}

export function getProjectsByService(serviceSlug: string) {
  return projects.filter((p) => p.serviceSlugsDelivered.includes(serviceSlug));
}

export function getRelatedProjects(project: Project, limit = 3) {
  const related = project.relatedProjectSlugs
    .map((slug) => getProjectBySlug(slug))
    .filter((p): p is Project => Boolean(p));
  if (related.length >= limit) return related.slice(0, limit);
  const sameIndustry = projects.filter(
    (p) => p.slug !== project.slug && p.industrySlug === project.industrySlug && !related.includes(p)
  );
  return [...related, ...sameIndustry].slice(0, limit);
}
