import type { Project } from "./types";

/**
 * Source: Master Source of Truth §9 (Initial project database) for the five
 * projects with fuller scope descriptions, and the brochure's "Our Landmark
 * Projects" photo captions (pp. 39–43) for the lighter portfolio entries —
 * name, client and location only, since the brochure gives no further scope
 * detail for those. No challenge/engineering-approach/outcome narrative is
 * invented anywhere below; fields with no supplied source content are left
 * undefined so the case-study template renders an honest empty state rather
 * than fabricated prose. Huawei Technologies Nepal is deliberately excluded
 * despite appearing in the brochure photo grid — the client questionnaire
 * (the higher-authority, more recent source) states Huawei should not be
 * photographed/publicised. See docs/OPEN_DECISIONS.md #4–#5.
 */
export const projects: Project[] = [
  {
    slug: "ncell-corporate-office",
    name: "Ncell Corporate Office",
    client: "Ncell",
    clientDisplayApproved: true,
    location: "Lainchaur, Kathmandu",
    industrySlug: "telecom-data-centres",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "HVAC and MEP works for the new corporate office.",
    servicesDelivered: ["HVAC", "MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health"],
    // Reconciled with "Ncell Iconic Building, Kathmandu" (AIPL PROFILE - 2026.pptx, slide 8)
    // per docs/AIRTECH_CONTENT_AUDIT.md §2d — same client, treated as the same entry.
    heroImage: { src: "/images/projects/ncell-iconic-building.jpg", alt: "Ncell Iconic Building, Kathmandu" },
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health"],
    relatedProjectSlugs: ["sipradi-trading"],
    featured: true,
    seo: {
      title: "Ncell Corporate Office: HVAC & MEP",
      description: "HVAC and MEP works delivered for the Ncell corporate office in Lainchaur, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "sipradi-trading",
    name: "Sipradi Trading Corporate Office",
    client: "Sipradi Trading Pvt. Ltd.",
    clientDisplayApproved: true,
    location: "Gairidhara, Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "Complete MEP and HVAC works for the new office building.",
    servicesDelivered: ["Complete MEP", "HVAC"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["ncell-corporate-office"],
    featured: true,
    seo: {
      title: "Sipradi Trading Corporate Office: Complete MEP",
      description: "Complete MEP and HVAC works delivered for the Sipradi Trading office building in Gairidhara, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "new-airport-commercial-office-parking",
    name: "New Airport Commercial Office & Parking Lot",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Infrastructure / commercial",
    projectStatus: "provisional",
    airtechRole: "MEP works for the commercial office and parking facility.",
    servicesDelivered: ["MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health"],
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "New Airport Commercial Office & Parking: MEP",
      description: "MEP works for the new airport commercial office and parking lot facility in Kathmandu.",
    },
    status: "needs_verification",
  },
  {
    slug: "nobel-college-health-education",
    name: "Nobel College of Health and Education Foundation",
    client: "Nobel College of Health and Education Foundation",
    clientDisplayApproved: true,
    location: "Baneshwor, Kathmandu",
    industrySlug: "education-institutional",
    projectType: "Healthcare / education",
    projectStatus: "provisional",
    airtechRole: "MEP works including supply, delivery, installation, testing and commissioning.",
    servicesDelivered: ["MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["nepal-mediciti"],
    featured: true,
    seo: {
      title: "Nobel College of Health and Education Foundation: MEP",
      description: "MEP works including supply, delivery, installation, testing and commissioning at Nobel College, Baneshwor, Kathmandu.",
    },
    status: "source_only",
  },
  {
    slug: "nepal-mediciti",
    name: "Nepal Mediciti / Ashwin's Medical College & Hospital",
    client: "Nepal Mediciti / Ashwin's Medical College & Hospital",
    clientDisplayApproved: true,
    location: "Lalitpur, Nepal",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "provisional",
    airtechRole: "HVAC/MEP engineering and execution.",
    servicesDelivered: ["HVAC", "MEP"],
    serviceSlugsDelivered: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    heroImage: { src: "/images/projects/nepal-mediciti-hospital.jpg", alt: "Nepal Mediciti hospital, Lalitpur" },
    gallery: [],
    relatedServiceSlugs: ["hvac", "electrical", "plumbing-public-health", "fire-protection"],
    relatedProjectSlugs: ["nobel-college-health-education"],
    featured: true,
    seo: {
      title: "Nepal Mediciti Hospital: HVAC & MEP",
      description: "HVAC/MEP engineering and execution at Nepal Mediciti / Ashwin's Medical College & Hospital.",
    },
    status: "needs_verification",
  },
  // Lighter portfolio entries — brochure "Our Landmark Projects" photo captions only.
  // No scope narrative supplied, so challenge/approach/outcome fields are omitted.
  {
    slug: "norvic-international-hospital",
    name: "Norvic International Hospital",
    client: "Norvic International Hospital",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Norvic International Hospital",
      description: "Norvic International Hospital, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "grande-international-hospital",
    name: "Grande International Hospital",
    client: "Grande International Hospital",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "healthcare",
    projectType: "Hospital",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Grande International Hospital",
      description: "Grande International Hospital, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "the-soaltee",
    name: "The Soaltee",
    client: "Soaltee",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["radisson-hotel-kathmandu"],
    featured: false,
    seo: {
      title: "The Soaltee, Kathmandu",
      description: "The Soaltee, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "radisson-hotel-kathmandu",
    name: "Radisson Hotel Kathmandu",
    client: "Hotel Radisson",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["the-soaltee"],
    featured: false,
    seo: {
      title: "Radisson Hotel Kathmandu",
      description: "Radisson Hotel, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "universal-college-medical-sciences",
    name: "Universal College of Medical Sciences",
    client: "Universal College of Medical Sciences",
    clientDisplayApproved: true,
    location: "Bhairahawa",
    industrySlug: "education-institutional",
    projectType: "Educational / medical college",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Universal College of Medical Sciences",
      description: "Universal College of Medical Sciences, Bhairahawa. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "shanker-group-corporate-office",
    name: "Shanker Group Corporate Office",
    client: "Shanker Group",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Shanker Group Corporate Office",
      description: "Shanker Group Corporate Office, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "caan-civil-aviation-authority",
    name: "CAAN Office Building",
    client: "Civil Aviation Authority of Nepal",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Infrastructure / institutional",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    // AIPL PROFILE - 2026.pptx, slide 8 — "CAAN Office Building, Kathmandu".
    heroImage: { src: "/images/projects/caan-office-building.jpg", alt: "CAAN Office Building, Kathmandu" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["new-airport-commercial-office-parking"],
    featured: true,
    seo: {
      title: "Civil Aviation Authority of Nepal (CAAN)",
      description: "Civil Aviation Authority of Nepal (CAAN), Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "laxmi-motor-corporation",
    name: "Laxmi Motors KD Plant",
    client: "Laxmi Motor Corporation",
    clientDisplayApproved: true,
    location: "Parasi, Nepal",
    industrySlug: "industrial",
    projectType: "Industrial facility",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    // AIPL PROFILE - 2026.pptx, slide 8 — "Laxmi Motors KD Plant, Parasi"; reconciled with the
    // existing "Laxmi Motor Corporation" client record per docs/AIRTECH_CONTENT_AUDIT.md §2d.
    heroImage: { src: "/images/projects/laxmi-motors-kd-plant.jpg", alt: "Laxmi Motors KD Plant, Parasi" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Laxmi Motor Corporation",
      description: "Laxmi Motor Corporation, Parasi. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  // Extended landmark list — AIPL PROFILE - 2026.pptx slides 8–11, "Our Landmark
  // Projects" (name + location only, no scope given in the source). Same
  // minimal, non-fabricated pattern as the entries above. See
  // docs/AIRTECH_CONTENT_AUDIT.md §2d.
  {
    slug: "tiger-palace-resort",
    name: "Tiger Palace Resort",
    client: "Tiger Palace Resort & Casino",
    clientDisplayApproved: true,
    location: "Bhairahawa, Nepal",
    industrySlug: "hospitality",
    projectType: "Resort & casino",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/tiger-palace-resort.jpg", alt: "Tiger Palace Resort, Bhairahawa" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["dusit-princess", "hyatt-centric"],
    featured: true,
    seo: {
      title: "Tiger Palace Resort",
      description: "Tiger Palace Resort, Bhairahawa. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "chandragiri-hills-resort",
    name: "Chandragiri Hills Resort",
    client: "Chandragiri Hills Resort",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Resort",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/chandragiri-hills-resort.jpg", alt: "Chandragiri Hills Resort, Kathmandu" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["tiger-palace-resort"],
    featured: true,
    seo: {
      title: "Chandragiri Hills Resort",
      description: "Chandragiri Hills Resort, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "dusit-princess",
    name: "Dusit Princess",
    client: "Dusit Princess",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/dusit-princess.jpg", alt: "Dusit Princess, Kathmandu" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["tiger-palace-resort", "hyatt-centric"],
    featured: true,
    seo: {
      title: "Dusit Princess, Kathmandu",
      description: "Dusit Princess, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hyatt-centric",
    name: "Hyatt Centric",
    client: "Hyatt Centric",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/hyatt-centric.jpg", alt: "Hyatt Centric, Kathmandu" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: ["dusit-princess", "tiger-palace-resort"],
    featured: true,
    seo: {
      title: "Hyatt Centric, Kathmandu",
      description: "Hyatt Centric, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "skyline-mall-birgunj",
    name: "Skyline Mall",
    client: "Skyline Mall",
    clientDisplayApproved: true,
    location: "Birgunj, Nepal",
    industrySlug: "corporate-commercial",
    projectType: "Retail / commercial",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    heroImage: { src: "/images/landmarks/skyline-mall-birgunj.jpg", alt: "Skyline Mall, Birgunj" },
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: true,
    seo: {
      title: "Skyline Mall, Birgunj",
      description: "Skyline Mall, Birgunj. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "holiday-inn-express",
    name: "Holiday Inn Express",
    client: "Holiday Inn Express",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Holiday Inn Express, Kathmandu",
      description: "Holiday Inn Express, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hotel-yak-and-yeti",
    name: "Hotel Yak & Yeti",
    client: "Hotel Yak & Yeti",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Hotel Yak & Yeti, Kathmandu",
      description: "Hotel Yak & Yeti, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hgi-corporate-office",
    name: "HGI Corporate Office",
    client: "HGI",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Corporate office",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "HGI Corporate Office, Kathmandu",
      description: "HGI Corporate Office, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    // Explicitly marked "(Ongoing)" in the source — never present as a
    // completed case study. See docs/AIRTECH_CONTENT_AUDIT.md §2d.
    slug: "parliament-building",
    name: "Parliament Building",
    clientDisplayApproved: false,
    location: "Kathmandu",
    industrySlug: "corporate-commercial",
    projectType: "Government / institutional building",
    projectStatus: "ongoing",
    airtechRole: "Ongoing project featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Parliament Building, Kathmandu (Ongoing)",
      description: "Parliament Building, Kathmandu — an ongoing project in Airtech's portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "hotel-hilton-naxal",
    name: "Hotel Hilton",
    client: "Hotel Hilton",
    clientDisplayApproved: true,
    location: "Naxal, Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Hotel Hilton, Naxal",
      description: "Hotel Hilton, Naxal, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "the-terraces-resort-spa",
    name: "The Terraces Resort & Spa",
    client: "The Terraces Resort & Spa",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Resort & spa",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "The Terraces Resort & Spa, Kathmandu",
      description: "The Terraces Resort & Spa, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
  {
    slug: "nepali-ghar-hotel",
    name: "Nepali Ghar Hotel",
    client: "Nepali Ghar Hotel",
    clientDisplayApproved: true,
    location: "Kathmandu",
    industrySlug: "hospitality",
    projectType: "Hotel",
    projectStatus: "provisional",
    airtechRole: "Featured in Airtech's project portfolio.",
    servicesDelivered: [],
    serviceSlugsDelivered: ["hvac"],
    gallery: [],
    relatedServiceSlugs: ["hvac"],
    relatedProjectSlugs: [],
    featured: false,
    seo: {
      title: "Nepali Ghar Hotel, Kathmandu",
      description: "Nepali Ghar Hotel, Kathmandu. Featured in Airtech's project portfolio.",
    },
    status: "source_only",
  },
];

export function getProjects() {
  return projects;
}

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}

export function getFeaturedProjects() {
  return projects.filter((p) => p.featured);
}

export function getProjectsByIndustry(industrySlug: string) {
  return projects.filter((p) => p.industrySlug === industrySlug);
}

export function getProjectsByService(serviceSlug: string) {
  return projects.filter((p) => p.serviceSlugsDelivered.includes(serviceSlug));
}

export function getRelatedProjects(project: Project, limit = 3) {
  const related = project.relatedProjectSlugs
    .map((slug) => getProjectBySlug(slug))
    .filter((p): p is Project => Boolean(p));
  if (related.length >= limit) return related.slice(0, limit);
  const sameIndustry = projects.filter(
    (p) => p.slug !== project.slug && p.industrySlug === project.industrySlug && !related.includes(p)
  );
  return [...related, ...sameIndustry].slice(0, limit);
}
